# Generated by OmopViewer 0.4.0
# Be careful editing this file

library(shiny)
library(omopgenerics)
library(reactable)
library(dplyr)
library(OmopCheckout)
library(shinycssloaders)
library(commonmark)
library(bslib)
library(rlang)

options(shiny.maxRequestSize = 500 * 1024^2)
# source functions
source(file.path(getwd(), "functions.R"))
