
server <- function(input, output, session) {

  # result processing ----
  explore_results <- shiny::reactiveVal(list())
  summary_results <- shiny::reactiveVal(list())
  checkout_md <- shiny::reactiveVal()

  # Helper: append a line directly to the UI output, bypassing reactive batching
  log_msg <- function(msg) {
    line <- paste0("[", format(Sys.time(), "%H:%M:%S"), "] ", msg, "\n")
    shinyjs::html(id = "processing_log", html = line, add = TRUE)
  }

  # Observe file upload and trigger processing
  shiny::observeEvent(input$file_results, {

    # Collapse the upload accordion now that a file has been provided
    bslib::accordion_panel_close("upload_accordion", "Upload Summarised Results")

    # Clear the log box, show processing panel, hide results
    shinyjs::html("processing_log", "")
    shinyjs::show("results_processing_wrapper")
    shinyjs::hide("results_summary_wrapper")

    log_msg("File received. Starting processing...")

    tryCatch({

      log_msg(paste0("Reading file: ", input$file_results$name))
      results <- readr::read_csv(input$file_results$datapath, show_col_types = FALSE)

      log_msg("Attempting to convert file to `summarised_result` object.")
      results <- omopgenerics::newSummarisedResult(x = results)

      log_msg("Splitting result by result type.")
      rt <- unique(omopgenerics::settings(results)$result_type) |>
        rlang::set_names() |>
        purrr::map(\(resType) {
          results |>
            omopgenerics::filterSettings(.data$result_type == .env$resType) |>
            omopgenerics::tidy()
        })
      explore_results(rt)

      # update options in ui
      shinyWidgets::updatePickerInput(
        inputId = "result_type",
        choices = names(rt),
        selected = names(rt)[1]
      )

      log_msg("Creating summary by result_type.")
      rt <- omopgenerics::settings(results) |>
        dplyr::distinct(.data$package_name, .data$result_type, .data$package_version) |>
        dplyr::left_join(pkgsInfo, by = "package_name") |>
        dplyr::left_join(resultTypeInfo, by = "result_type")
      rt <- rt$result_type |>
        unique() |>
        rlang::set_names() |>
        purrr::map(\(resType) {
          x <- rt |>
            dplyr::filter(.data$result_type == .env$resType)
          version <- paste0(sort(x$package_version), collapse = "; ")
          x <- x |>
            dplyr::select(!"package_version") |>
            dplyr::distinct()
          if (nrow(x) > 1) {
            browser()
          }
          if (!is.na(x$package_name)) {
            pkg <- paste0("[", x$package_name, "](", x$package_website, ")")
          } else {
            pkg <- "Unknown"
          }
          if (!is.na(x$function_name)) {
            moreInfo <- paste0(" See <", x$package_website, "reference/", x$function_name, ".html>.")
          } else {
            moreInfo <- ""
          }
          paste0(
            "This results were generated by ", pkg, " (", version, ").",
            moreInfo
          )
        })
      summary_results(rt)

      log_msg("Creating create checkout report.")
      checkout_md(OmopCheckout::checkout(results, output = "text"))

      log_msg("Processing complete.")

      # Hide processing panel and reveal summary panel
      shinyjs::hide("results_processing_wrapper")
      shinyjs::show("results_summary_wrapper")

    }, error = function(e) {
      log_msg(paste0("ERROR: ", conditionMessage(e)))
      # Keep the processing panel open so the user can read the error
    })

  })

  # result explorer ----
  output$result_type_generation <- shiny::renderUI({
    summary_results()[[input$result_type]] |>
      markdown::markdownToHTML(fragment.only = TRUE) |>
      shiny::HTML()
  })

  output$results_contents <- reactable::renderReactable({
    reactable::reactable(explore_results()[[input$result_type]])
  })

  # check out summary ----
  output$checkout_summary_md <- shiny::renderText({
    paste(checkout_md(), collapse = "\n")
  })

  output$download_checkout_md <- shiny::downloadHandler(
    filename = function() paste0("checkout_summary_", Sys.Date(), ".md"),
    content = function(file) writeLines(checkout_md(), con = file)
  )

  output$checkout_summary_html <- shiny::renderUI({
    md <- paste(checkout_md(), collapse = "\n\n")
    html <- markdown::markdownToHTML(text = md, fragment.only = TRUE)
    shiny::HTML(html)
  })
}
