# Generated by OmopViewer 0.4.0
# Be careful editing this file

ui <- bslib::page_navbar(
  title = shiny::tags$span(
    shiny::tags$img(
      src = "hdruk_logo.svg",
      width = "auto",
      height = "46px",
      class = "me-3",
      alt = "logo"
    ),
    ""
  ),
  theme = bslib::bs_theme(bootswatch = "flatly"),
  bslib::nav_panel(
    title = "Background",
    icon = shiny::icon("book-atlas"),
    backgroundCard("background.md")
  ),
  bslib::nav_panel(
    title = "OmopCheckout",
    icon = shiny::icon("magnifying-glass-chart"),

    fileInput(
      "file_results",
      "Upload Summarised Results",
      accept = c(".csv")
    ),

    bslib::navset_tab(

      bslib::nav_panel(
        title = "Explore Results",
        tags$h3("Summarised Results"),
        shinycssloaders::withSpinner(reactable::reactableOutput("results_contents")),

        verbatimTextOutput("debug_uploaded")
      ),

      # inside your OmopCheckout navset_tab / nav_panel
      bslib::nav_panel(
        title = "Checkout Summary",
       # tags$h3("Checkout Summary"),
        # main output rendered by server as structured UI
        uiOutput("checkout_summary_html")%>% shinycssloaders::withSpinner(type = 1, color = "#0d6efd"),
        # Raw markdown collapsible + download
        tags$details(
          tags$summary("Show raw markdown report"),
          verbatimTextOutput("checkout_summary_md")
        ),
        downloadButton("download_checkout_md", "Download summary (.md)")
      )

    )
  ),
  bslib::nav_spacer(),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("download"),
      shiny::downloadButton(
        outputId = "download_raw",
        label = "Download raw data",
        icon = shiny::icon("download")
      )
    )
  ),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("circle-info"),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.4.0")
    )
  ),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
)
