# server.R
# Generated by OmopViewer 0.4.0
# Be careful editing this file

server <- function(input, output, session) {
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      # Be careful: 'data' must exist here. As a safe fallback, export the uploaded table if available:
      df <- NULL
      try({
        df <- getUploadedResults()
      }, silent = TRUE)
      
      if (!is.null(df) && is.data.frame(df)) {
        utils::write.csv(df, file, row.names = FALSE)
      } else {
        # fallback: if your original code expects a specific pipeline, restore it here.
        writeLines("no data available", file)
      }
    }
  )
  
  # Reactive: import uploaded file and coerce to data.frame if possible
  getUploadedResults <- shiny::reactive({
    req(input$file_results)
    infile <- input$file_results
    path <- infile$datapath
    name <- infile$name
    
    message("Uploading file: ", name, " -> ", path)
    
    # try import - capture errors cleanly
    imported <- NULL
    import_err <- NULL
    tryCatch({
      imported <- omopgenerics::importSummarisedResult(path)
    }, error = function(e) {
      import_err <<- e
      message("omopgenerics import error: ", conditionMessage(e))
    }, warning = function(w) {
      message("omopgenerics import warning: ", conditionMessage(w))
    })
    
    # If omopgenerics failed, try a simple CSV reader fallback so you can test the UI
    if (is.null(imported)) {
      message("Falling back to vroom for testing (replace with omopgenerics if needed).")
      try({
        imported <- vroom::vroom(path, show_col_types = FALSE, progress = FALSE)
      }, silent = TRUE)
    }
    
    if (is.null(imported)) {
      showNotification("Failed to import file. Check R console for details.", type = "error", duration = 6)
      stop("Import failed for file: ", path)
    }
    
    # If it returned a list-like or S3 object, try to extract a data.frame
    # common patterns: imported$results, imported[[1]] (list with first element df)
    if (!is.data.frame(imported)) {
      # If it's a list with a data.frame inside, try to find it
      if (is.list(imported)) {
        if (!is.null(imported$results) && is.data.frame(imported$results)) {
          imported <- imported$results
          message("Extracted imported$results as data.frame")
        } else if (length(imported) >= 1 && is.data.frame(imported[[1]])) {
          imported <- imported[[1]]
          message("Extracted imported[[1]] as data.frame")
        } else {
          # try coercion
          try({
            imported <- as.data.frame(imported)
            message("Coerced imported object to data.frame with as.data.frame()")
          }, silent = TRUE)
        }
      } else {
        # If it's S3, try to find a data.frame field or method
        # Print class to console for debugging
        message("Imported object class: ", paste(class(imported), collapse = ", "))
        # try as.data.frame fallback
        try({
          imported <- as.data.frame(imported)
          message("Coerced S3 imported object to data.frame using as.data.frame()")
        }, silent = TRUE)
      }
    }
    
    # At this point, if it's not a data.frame, abort with clear message
    if (!is.data.frame(imported)) {
      message("Final imported object is not a data.frame. Class: ", paste(class(imported), collapse = ", "))
      showNotification("Imported object is not a data.frame — see R console for details.", type = "error", duration = 8)
      stop("Imported object is not a data.frame. Class: ", paste(class(imported), collapse = ", "))
    }
    
    # Convert list-columns to plain text for safe display
    if (any(vapply(imported, is.list, logical(1)))) {
      imported[] <- lapply(imported, function(col) {
        if (is.list(col)) vapply(col, function(x) {
          if (is.null(x)) "" else paste0(as.character(x), collapse = "; ")
        }, FUN.VALUE = character(1)) else col
      })
      message("Converted list-columns to character for display.")
    }
    
    message("Imported data.frame rows=", nrow(imported), " cols=", ncol(imported))
    imported
  })
  
  # Render debug text in UI if you add verbatimTextOutput("debug_uploaded")
  output$debug_uploaded <- renderPrint({
    if (is.null(input$file_results)) return("No file uploaded yet.")
    tryCatch({
      d <- getUploadedResults()
      paste0("Imported class=", paste(class(d), collapse = ", "),
             "  Rows=", nrow(d), "  Cols=", ncol(d))
    }, error = function(e) {
      paste("Import error:", conditionMessage(e))
    })
  })
  
  # render the reactable table (must match UI id 'results_contents')
  output$results_contents <- reactable::renderReactable({
    req(input$file_results)
    df <- getUploadedResults()
    validate(
      need(is.data.frame(df), "Imported object is not a data.frame/tibble."),
      need(nrow(df) > 0, "Uploaded file contains no rows")
    )
    # Limit columns if extremely wide to avoid browser problems
    if (ncol(df) > 120) {
      showNotification("Data has many columns; showing first 120 for responsiveness.", type = "message", duration = 4)
      df <- df[, seq_len(120), drop = FALSE]
    }
    reactable::reactable(df, searchable = TRUE, filterable = TRUE, pagination = TRUE, defaultPageSize = 25)
  })
  
  # reactive that returns the markdown lines (character vector)
  checkout_md <- shiny::reactive({
    req(input$file_results)
    df <- getUploadedResults()
    
    # capture printed output because checkoutSummary() uses cat() then returns invisibly
    md_lines <- tryCatch(
      {
        capture.output({
          
           omopcheckout::checkoutSummary(df)
         
        })
      },
      error = function(e) {
        c("# Error generating checkout summary", "", paste0("Error: ", conditionMessage(e)))
      }
    )
    
    # ensure it's a character vector
    if (is.null(md_lines)) md_lines <- character(0)
    md_lines
  })
  
  # render HTML in the tab (convert markdown -> HTML)
  output$checkout_summary_html <- shiny::renderUI({
    md <- checkout_md()
    html_fragment <- tryCatch(
      commonmark::markdown_html(paste(md, collapse = "\n")),
      error = function(e) paste0("<pre>Failed to render markdown: ", htmltools::htmlEscape(conditionMessage(e)), "</pre>")
    )
    htmltools::HTML(html_fragment)
  })
  
  # show raw markdown in a verbatim block
  output$checkout_summary_md <- shiny::renderText({
    paste(checkout_md(), collapse = "\n")
  })
  
  # download handler to export the markdown file
  output$download_checkout_md <- shiny::downloadHandler(
    filename = function() {
      paste0("checkout_summary_", Sys.Date(), ".md")
    },
    content = function(file) {
      md <- checkout_md()
      writeLines(md, con = file)
    }
  )
  
}