# .github/workflows/create_package.yaml
name: create_package.yaml

on:
  push:
    branches: main
  workflow_dispatch:

permissions: write-all

jobs:
  create_package:
    if: ${{ !(github.event.repository.name == 'EmptyPackageTemplate' && github.repository_owner == 'oxford-pharmacoepi') }}
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create gh-pages branch
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          echo "# GitHub Pages" > README.md
          git add README.md
          git commit -m "Initialize empty gh-pages branch"
          git push origin gh-pages
          git checkout main

      - name: Remove files
        run: |
          rm README.md
          rm extras/new_repo.png
          rm .github/workflows/create_package.yaml

      - name: Create new readme
        run: |
          mv extras/FUTURE_README.md README.md
          mv extras/FUTURE_README.Rmd README.Rmd

      - name: Correct names
        env:
          REPO_NAME: ${{ github.event.repository.name }}
          REPO_OWNER: ${{ github.repository_owner }}
        run: |
          echo "Replacing placeholders with repo name and owner..."
          find . -type f -not -path '*/\.git/*' -exec sed -i \
            -e "s/EmptyPackage/${REPO_NAME}/g" \
            -e "s/oxford-pharmacoepi/${REPO_OWNER}/g" {} +
          echo "Replacements complete."

      - name: Commit & push changes to main
        run: |
          git add -A
          git commit -m "Setup package"
          git push origin HEAD:main

  check_package:
    needs: create_package
    uses: ./.github/workflows/R-CMD-check.yaml

  create_website:
    needs: create_package
    uses: ./.github/workflows/pkgdown.yaml
